id = "zap-language"
name = "Zap Language"
version = "0.1.0"
schema_version = 1
authors = ["Filip Tibell <filip.tibell@example.com>"]
description = "Zap language support for Zed"
repository = "https://github.com/filiptibell/zap-language-server"

[grammars.zap]
repository = "https://github.com/filiptibell/tree-sitter-zap"
rev = "d7ea48f7ea6050eb67b1c7d28ab12672c9bcc1a2"

[language_servers.zap-language-server]
name = "Zap Language Server"
languages = ["Zap"]
